version: '3.8'

services:
  # ChromaDB Service
  chroma:
    build: ./chroma-service
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - rag-network

  # Backend API Service  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    env_file:
      - ./backend/.env
    depends_on:
      - chroma
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    networks:
      - rag-network

  # Frontend Service (for development)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rag-network

volumes:
  chroma_data:
  backend_uploads:

networks:
  rag-network:
    driver: bridge 